version: 2.1
commands:
  install_build_env:
    parameters:
      compiler:
        default: gcc-c++
        type: string
    steps:
      - run:
          name: Install build environment
          command: |
            dnf install -y --nodocs \
              << parameters.compiler >> \
              boost-devel \
              cmake \
              doxygen \
              git \
              graphviz-devel \
              lcov \
              make \
              protobuf-devel \
              range-v3-devel \
              spdlog-devel
  build:
    steps:
      - run:
          name: Build the project
          command: cmake -B build -DBUILD_BENCHMARKS=ON && cmake --build build -j $(($(nproc)/8))
  test:
    steps:
      - run:
          name: Run tests
          working_directory: build
          command: CTEST_OUTPUT_ON_FAILURE=1 ctest
      - run:
          name: Build documentation
          working_directory: build
          command: make doc
  generate_coverage:
    steps:
      - run:
          name: Generate coverage report
          command: |
            cmake -B build_coverage -DCMAKE_BUILD_TYPE=Debug -DCOVERAGE=ON && \
            CTEST_OUTPUT_ON_FAILURE=1 cmake --build build_coverage -j $(($(nproc)/8)) --target coverage && \
            bash <(curl -s https://codecov.io/bash)

jobs:
  build_gcc:
    docker:
      - image: fedora:33
    steps:
      - install_build_env
      - checkout
      - build
      - test
  build_clang:
    docker:
      - image: fedora:33
    environment:
      CXX: /usr/bin/clang++
      CC: /usr/bin/clang
    steps:
      - install_build_env:
          compiler: clang
      - checkout
      - build
      - test
  generate_coverage:
    docker:
      - image: fedora:33
    steps:
      - install_build_env
      - checkout
      - generate_coverage

workflows:
  build:
    jobs:
      - build_gcc
      - build_clang
      - generate_coverage
