version: 2.1
commands:
  install_build_env:
    parameters:
      compiler:
        default: gcc-c++
        type: string
    steps:
      - run:
          name: Install build environment
          command: |
            dnf install -y --nodocs \
              << parameters.compiler >> \
              boost-devel \
              catch-devel \
              cmake \
              doxygen \
              git \
              lcov \
              make \
              python3-pip \
              range-v3-devel \
              spdlog-devel
  build:
    steps:
      - run:
          name: Build the project
          command: cmake -B build && cmake --build build -j`nproc`
  test:
    steps:
      - run:
          name: Run tests
          working_directory: build
          command: ctest
      - run:
          name: Build documentation
          working_directory: build
          command: make doc


jobs:
  build_gcc:
    docker:
      - image: fedora:33
    steps:
      - install_build_env
      - checkout
      - build
      - test
      - run:
          name: Generate coverage report
          command: |
            cmake -B build_coverage -DCMAKE_BUILD_TYPE=Debug -DCOVERAGE=ON && \
            cmake --build build_coverage -j1 --target coverage && \
            bash <(curl -s https://codecov.io/bash)
  build_clang:
    docker:
      - image: fedora:33
    environment:
      CXX: /usr/bin/clang++
      CC: /usr/bin/clang
    steps:
      - install_build_env:
          compiler: clang
      - checkout
      - build
      - test

workflows:
  build:
    jobs:
      - build_gcc
      - build_clang
